encoding: utf-8

# Site settings
title: Dr. Kormos Zsuzsanna | ügyvéd
legal: Minden jog fenntartva
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# contact info
name: Dr. Kormos Zsuzsanna
work: ügyvéd
email: info@drkormos.hu
address: 1132 Budapest, Váci út 28. fe. 2.
phone: +36 1 373 0530
phone_link: +3613730530
mobile: +36 30 830 6832
mobile_link: +36308306832

# meta
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://drkormos.hu" # the base hostname & protocol for your site, e.g. http://example.com

